# Generated by Django 2.2.5 on 2020-01-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
