# Generated by Django 2.2.5 on 2020-01-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_data', '0002_auto_20200118_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(max_length=250)),
                ('loan', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=250)),
                ('mobile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='customer_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('item', models.CharField(default=0, max_length=250)),
                ('value', models.IntegerField(default=0)),
                ('mobile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('operation', models.CharField(max_length=250)),
                ('value', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='customer_data',
        ),
        migrations.DeleteModel(
            name='txn_data',
        ),
    ]
