# Generated by Django 2.2.5 on 2020-01-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_data', '0004_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_list',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer_values',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer_values',
            name='item',
        ),
        migrations.RemoveField(
            model_name='customer_values',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer_values',
            name='value',
        ),
        migrations.AddField(
            model_name='customer_values',
            name='ecar_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_values',
            name='penalty_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_values',
            name='tchallan_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_values',
            name='ubill_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_values',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer_list',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
