# Generated by Django 2.2.5 on 2020-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_data', '0005_auto_20200118_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='item',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='value',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='weight',
        ),
        migrations.AddField(
            model_name='rules',
            name='ecar_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rules',
            name='ecar_wt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rules',
            name='penalty_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rules',
            name='penalty_wt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rules',
            name='tchallan_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rules',
            name='tchallan_wt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rules',
            name='threshold_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rules',
            name='threshold_wt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rules',
            name='ubill_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rules',
            name='ubill_wt',
            field=models.FloatField(default=0),
        ),
    ]
