# Generated by Django 2.2.5 on 2020-01-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_data', '0006_auto_20200118_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='rule_id',
            field=models.IntegerField(default=1),
        ),
    ]
