# Generated by Django 2.2.5 on 2020-01-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_data', '0007_rules_rule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
