# Generated by Django 2.2.5 on 2020-01-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate_data', '0008_decision_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='status',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
